### ISSUE TITLE
Issues running

### ISSUE THREAD

**Issue by andku85** [Rishi-Bidani/manga-downloader#1]
I tried running this in VSCode with the python extension. and I am getting errors on Line 1 and 2. 

The error. when i try running main.py
import requests
ModuleNotFoundError: No module named 'requests'

Sorry i am new to python. will this ask for a prompt or am i supposed to replace something in the code?
can you show a sample of the command.

**Comment by Rishi-Bidani** [comment]
Hey, you will need to install the `requests` module via pip (you can google the error).
Furthermore, I haven't maintained this repository in a while so I cannot guarantee whether it will work (you might have to play around with the class names)
Finally, if you are able to download the manga, do check out my mangaviewer repository :)
